//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let reuseIdentifier = reuseIdentifier()

  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 64 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `LaunchScreen`.
    var launchScreen: RswiftResources.ImageResource { .init(name: "LaunchScreen", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `add`.
    var add: RswiftResources.ImageResource { .init(name: "add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `add_select`.
    var add_select: RswiftResources.ImageResource { .init(name: "add_select", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `algorithm`.
    var algorithm: RswiftResources.ImageResource { .init(name: "algorithm", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `book`.
    var book: RswiftResources.ImageResource { .init(name: "book", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `case`.
    var `case`: RswiftResources.ImageResource { .init(name: "case", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `defaultAvatar.jpg`.
    var defaultAvatarJpg: RswiftResources.ImageResource { .init(name: "defaultAvatar.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `design_pattern`.
    var design_pattern: RswiftResources.ImageResource { .init(name: "design_pattern", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `detailBg`.
    var detailBg: RswiftResources.ImageResource { .init(name: "detailBg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `download`.
    var download: RswiftResources.ImageResource { .init(name: "download", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `forrest-icon`.
    var forrestIcon: RswiftResources.ImageResource { .init(name: "forrest-icon", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `gy_assistant_active_select_box`.
    var gy_assistant_active_select_box: RswiftResources.ImageResource { .init(name: "gy_assistant_active_select_box", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_assistant_active_unselect_box`.
    var gy_assistant_active_unselect_box: RswiftResources.ImageResource { .init(name: "gy_assistant_active_unselect_box", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_bar_close_video`.
    var gy_chat_bar_close_video: RswiftResources.ImageResource { .init(name: "gy_chat_bar_close_video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_bar_play_video`.
    var gy_chat_bar_play_video: RswiftResources.ImageResource { .init(name: "gy_chat_bar_play_video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_bar_stop_video`.
    var gy_chat_bar_stop_video: RswiftResources.ImageResource { .init(name: "gy_chat_bar_stop_video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_btn_clock`.
    var gy_chat_btn_clock: RswiftResources.ImageResource { .init(name: "gy_chat_btn_clock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_commend_goods`.
    var gy_chat_commend_goods: RswiftResources.ImageResource { .init(name: "gy_chat_commend_goods", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_delivery_order`.
    var gy_chat_delivery_order: RswiftResources.ImageResource { .init(name: "gy_chat_delivery_order", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_expression`.
    var gy_chat_expression: RswiftResources.ImageResource { .init(name: "gy_chat_expression", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_icon_tag`.
    var gy_chat_icon_tag: RswiftResources.ImageResource { .init(name: "gy_chat_icon_tag", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_more_album`.
    var gy_chat_more_album: RswiftResources.ImageResource { .init(name: "gy_chat_more_album", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_more_functions`.
    var gy_chat_more_functions: RswiftResources.ImageResource { .init(name: "gy_chat_more_functions", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_more_video`.
    var gy_chat_more_video: RswiftResources.ImageResource { .init(name: "gy_chat_more_video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_play_video`.
    var gy_chat_play_video: RswiftResources.ImageResource { .init(name: "gy_chat_play_video", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_push_activity`.
    var gy_chat_push_activity: RswiftResources.ImageResource { .init(name: "gy_chat_push_activity", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_redpackage`.
    var gy_chat_redpackage: RswiftResources.ImageResource { .init(name: "gy_chat_redpackage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_switch_group`.
    var gy_chat_switch_group: RswiftResources.ImageResource { .init(name: "gy_chat_switch_group", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_switch_keyboard`.
    var gy_chat_switch_keyboard: RswiftResources.ImageResource { .init(name: "gy_chat_switch_keyboard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_switch_voice`.
    var gy_chat_switch_voice: RswiftResources.ImageResource { .init(name: "gy_chat_switch_voice", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_voice_left`.
    var gy_chat_voice_left: RswiftResources.ImageResource { .init(name: "gy_chat_voice_left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_chat_voice_right`.
    var gy_chat_voice_right: RswiftResources.ImageResource { .init(name: "gy_chat_voice_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gy_tool_user`.
    var gy_tool_user: RswiftResources.ImageResource { .init(name: "gy_tool_user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gyhs_bigDefaultImage`.
    var gyhs_bigDefaultImage: RswiftResources.ImageResource { .init(name: "gyhs_bigDefaultImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `hightImage`.
    var hightImage: RswiftResources.ImageResource { .init(name: "hightImage", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `home`.
    var home: RswiftResources.ImageResource { .init(name: "home", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `home_selected`.
    var home_selected: RswiftResources.ImageResource { .init(name: "home_selected", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_between`.
    var icon_between: RswiftResources.ImageResource { .init(name: "icon_between", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_cal`.
    var icon_cal: RswiftResources.ImageResource { .init(name: "icon_cal", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_column`.
    var icon_column: RswiftResources.ImageResource { .init(name: "icon_column", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_course`.
    var icon_course: RswiftResources.ImageResource { .init(name: "icon_course", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_document`.
    var icon_document: RswiftResources.ImageResource { .init(name: "icon_document", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_life`.
    var icon_life: RswiftResources.ImageResource { .init(name: "icon_life", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_live`.
    var icon_live: RswiftResources.ImageResource { .init(name: "icon_live", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_phone`.
    var icon_phone: RswiftResources.ImageResource { .init(name: "icon_phone", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_pwd`.
    var icon_pwd: RswiftResources.ImageResource { .init(name: "icon_pwd", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `icon_right_arrow`.
    var icon_right_arrow: RswiftResources.ImageResource { .init(name: "icon_right_arrow", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `manor.jpg`.
    var manorJpg: RswiftResources.ImageResource { .init(name: "manor.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `map_home`.
    var map_home: RswiftResources.ImageResource { .init(name: "map_home", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `mine`.
    var mine: RswiftResources.ImageResource { .init(name: "mine", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `mine_selected`.
    var mine_selected: RswiftResources.ImageResource { .init(name: "mine_selected", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `nav_btn_backs`.
    var nav_btn_backs: RswiftResources.ImageResource { .init(name: "nav_btn_backs", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `nav_btn_closed`.
    var nav_btn_closed: RswiftResources.ImageResource { .init(name: "nav_btn_closed", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `normalImage`.
    var normalImage: RswiftResources.ImageResource { .init(name: "normalImage", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `pig`.
    var pig: RswiftResources.ImageResource { .init(name: "pig", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `placeholder`.
    var placeholder: RswiftResources.ImageResource { .init(name: "placeholder", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `santa`.
    var santa: RswiftResources.ImageResource { .init(name: "santa", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `search`.
    var search: RswiftResources.ImageResource { .init(name: "search", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `send`.
    var send: RswiftResources.ImageResource { .init(name: "send", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `share`.
    var share: RswiftResources.ImageResource { .init(name: "share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `share_select`.
    var share_select: RswiftResources.ImageResource { .init(name: "share_select", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sherlock`.
    var sherlock: RswiftResources.ImageResource { .init(name: "sherlock", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `student`.
    var student: RswiftResources.ImageResource { .init(name: "student", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `yacht.jpg`.
    var yachtJpg: RswiftResources.ImageResource { .init(name: "yacht.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 41 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `README.md`.
    var readmeMd: RswiftResources.FileResource { .init(name: "README", pathExtension: "md", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `README_en.md`.
    var readme_enMd: RswiftResources.FileResource { .init(name: "README_en", pathExtension: "md", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Shows.plist`.
    var showsPlist: RswiftResources.FileResource { .init(name: "Shows", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `algorithm@2x.png`.
    var algorithm2xPng: RswiftResources.FileResource { .init(name: "algorithm@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `book@2x.png`.
    var book2xPng: RswiftResources.FileResource { .init(name: "book@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `case@2x.png`.
    var case2xPng: RswiftResources.FileResource { .init(name: "case@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `defaultAvatar@2x.jpg`.
    var defaultAvatar2xJpg: RswiftResources.FileResource { .init(name: "defaultAvatar@2x", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `design_pattern@2x.png`.
    var design_pattern2xPng: RswiftResources.FileResource { .init(name: "design_pattern@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `detailBg@2x.png`.
    var detailBg2xPng: RswiftResources.FileResource { .init(name: "detailBg@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `forrest-icon.png`.
    var forrestIconPng: RswiftResources.FileResource { .init(name: "forrest-icon", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `forrest-icon.psd`.
    var forrestIconPsd: RswiftResources.FileResource { .init(name: "forrest-icon", pathExtension: "psd", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `hightImage@2x.png`.
    var hightImage2xPng: RswiftResources.FileResource { .init(name: "hightImage@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `hightImage@3x.png`.
    var hightImage3xPng: RswiftResources.FileResource { .init(name: "hightImage@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `home@2x.png`.
    var home2xPng: RswiftResources.FileResource { .init(name: "home@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `home_selected@2x.png`.
    var home_selected2xPng: RswiftResources.FileResource { .init(name: "home_selected@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_between@2x.png`.
    var icon_between2xPng: RswiftResources.FileResource { .init(name: "icon_between@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_cal@2x.png`.
    var icon_cal2xPng: RswiftResources.FileResource { .init(name: "icon_cal@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_column@2x.png`.
    var icon_column2xPng: RswiftResources.FileResource { .init(name: "icon_column@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_course@2x.png`.
    var icon_course2xPng: RswiftResources.FileResource { .init(name: "icon_course@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_document@2x.png`.
    var icon_document2xPng: RswiftResources.FileResource { .init(name: "icon_document@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_life@2x.png`.
    var icon_life2xPng: RswiftResources.FileResource { .init(name: "icon_life@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_live@2x.png`.
    var icon_live2xPng: RswiftResources.FileResource { .init(name: "icon_live@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_phone@2x.png`.
    var icon_phone2xPng: RswiftResources.FileResource { .init(name: "icon_phone@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_pwd@2x.png`.
    var icon_pwd2xPng: RswiftResources.FileResource { .init(name: "icon_pwd@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `icon_right_arrow@2x.png`.
    var icon_right_arrow2xPng: RswiftResources.FileResource { .init(name: "icon_right_arrow@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `manor.jpg`.
    var manorJpg: RswiftResources.FileResource { .init(name: "manor", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `map_home@2x.png`.
    var map_home2xPng: RswiftResources.FileResource { .init(name: "map_home@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `mine@2x.png`.
    var mine2xPng: RswiftResources.FileResource { .init(name: "mine@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `mine_selected@2x.png`.
    var mine_selected2xPng: RswiftResources.FileResource { .init(name: "mine_selected@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `nav_btn_backs@2x.png`.
    var nav_btn_backs2xPng: RswiftResources.FileResource { .init(name: "nav_btn_backs@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `nav_btn_closed@2x.png`.
    var nav_btn_closed2xPng: RswiftResources.FileResource { .init(name: "nav_btn_closed@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `normalImage@2x.png`.
    var normalImage2xPng: RswiftResources.FileResource { .init(name: "normalImage@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `normalImage@3x.png`.
    var normalImage3xPng: RswiftResources.FileResource { .init(name: "normalImage@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `pig.png`.
    var pigPng: RswiftResources.FileResource { .init(name: "pig", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `placeholder@2x.png`.
    var placeholder2xPng: RswiftResources.FileResource { .init(name: "placeholder@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `santa.png`.
    var santaPng: RswiftResources.FileResource { .init(name: "santa", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `search@2x.png`.
    var search2xPng: RswiftResources.FileResource { .init(name: "search@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `sherlock@3x.png`.
    var sherlock3xPng: RswiftResources.FileResource { .init(name: "sherlock@3x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `student@2x.png`.
    var student2xPng: RswiftResources.FileResource { .init(name: "student@2x", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `trie_data.txt`.
    var trie_dataTxt: RswiftResources.FileResource { .init(name: "trie_data", pathExtension: "txt", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `yacht.jpg`.
    var yachtJpg: RswiftResources.FileResource { .init(name: "yacht", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ChatListTableViewCell`.
    var chatListTableViewCell: RswiftResources.NibReferenceReuseIdentifier<ChatListTableViewCell, ChatListTableViewCell> { .init(name: "ChatListTableViewCell", bundle: bundle, identifier: "ChatListTableViewCell") }

    /// Nib `MessageSendTableViewCell`.
    var messageSendTableViewCell: RswiftResources.NibReference<MessageSendTableViewCell> { .init(name: "MessageSendTableViewCell", bundle: bundle) }

    /// Nib `MessageTableViewCell`.
    var messageTableViewCell: RswiftResources.NibReference<MessageTableViewCell> { .init(name: "MessageTableViewCell", bundle: bundle) }

    /// Nib `SCRecordPlayVC`.
    var scRecordPlayVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SCRecordPlayVC", bundle: bundle) }

    func validate() throws {

    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `ChatListTableViewCell`.
    let chatListTableViewCell: RswiftResources.ReuseIdentifier<ChatListTableViewCell> = .init(identifier: "ChatListTableViewCell")
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "LaunchScreen", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'LaunchScreen' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }
  }
}